trigger:
- master

pool:
  vmImage: 'ubuntu-latest'

steps:
- script: |
    apt-get update
    apt-get install -yy cdbs debhelper libgnomeui-dev scrollkeeper libxml-parser-perl libgcrypt-dev docbook-utils xmlto libglade2-dev
  displayName: 'Installing dependencies'

- script: |
    ./configure
  displayName: 'configure'

- script: |
    make
  displayName: 'make'